const state = () => ({
    articles: [
        {
            title: 'Peneliti Temukan Metabolisme Tubuh Tidak Menurun Hingga Usia 60',
            timestamp: '',
            description: 'Banyak yang beranggapan bahwa menjadi lebih sulit untuk menurunkan berat badan seiring bertambahnya usia. Tetapi sebuah studi baru telah membantah klaim tersebut, menunjukkan bahwa metabolisme tetap stabil antara usia 20 dan 60 tahun. Studi yang diterbitkan di jurnal Science, melihat data yang diambil dari 6.421 peserta selama 40 tahun, untuk melihat bagaimana faktor-faktor termasuk ukuran, jenis kelamin dan usia mempengaruhi metabolisme. Temuan menunjukkan bahwa sementara usia memang berperan dalam seberapa cepat orang membakar kalori, itu tidak memiliki banyak dampak pada metabolisme seperti yang diperkirakan sebelumnya.Tingkat metabolisme benar-benar stabil sepanjang kehidupan dewasa, 20 hingga 60 tahun, penulis studi Herman Pontzer, seorang profesor antropologi evolusi di Duke University di AS.“Tidak ada efek menopause yang bisa kita lihat, misalnya. Dan, Anda tahu, orang akan berkata, Saat saya menginjak usia 30 tahun, metabolisme saya berantakan. Kami tidak melihat bukti untuk itu, sebenarnya. Para peneliti menemukan bahwa total pengeluaran energi harian dan pengeluaran basal - energi yang dibutuhkan untuk menjalankan fungsi metabolisme mendasar seperti pernapasan - meningkat seiring dengan ukuran tubuh.Dengan mempertimbangkan hal ini, mereka menyimpulkan bahwa bayi hingga usia satu bulan menggunakan jumlah total energi yang sama per hari dengan orang dewasa, tetapi pada usia sekitar satu tahun, ini meningkat dengan cepat menjadi sekitar 50 persen lebih tinggi daripada orang dewasa.Namun, setelah usia tersebut, para peneliti menemukan bahwa total pengeluaran energi harian menurun secara perlahan melalui masa kanak-kanak dan remaja dengan laju sekitar -2,8 persen, hingga tingkat dewasa tercapai pada usia 20 tahun. Sejak usia 20 tahun, para peneliti menemukan bahwa total pengeluaran energi harian tetap stabil sampai sekitar usia 60 tahun, saat itu mulai menurun sekali lagi.Faktor-faktor termasuk kehamilan dan menopause tidak berpengaruh pada tingkat metabolisme, studi menyimpulkan. Para peneliti menyimpulkan bahwa anak-anak cenderung lebih aktif daripada orang dewasa, yang mengarah ke metabolisme yang lebih tinggi.&nbsp; Namun, remaja, terlepas dari stereotip bahwa mereka makan lebih banyak selama tahun-tahun pertumbuhan mereka, tidak memiliki tingkat metabolisme yang jauh lebih tinggi daripada orang dewasa. Sebelumnya ada anggapan bahwa metabolisme mungkin melambat di usia 30-an dan itu kemudian dianggap [menyebabkan] kerentanan terhadap penyebaran usia paruh baya, salah satu penulis studi, Profesor John Speakman dari University of Aberdeen di Inggris.&nbsp; Kami tidak menemukan bukti yang mendukung itu. Jadi, jika Anda menambah berat badan dan lingkar pinggang Anda membesar selama usia 30-an dan 40-an, itu mungkin karena Anda makan lebih banyak, lalu menghabiskan lebih sedikit energi, pungkasnya.',
            category: 'sehat a-z',
            image: 'metabolism-boost-article-1631057768.jpg',
            date: '07 Sep 2021'
        },
        {
            title: 'Apa Efek Suplemen Vitamin terhadap Sembelit ?',
            timestamp: '',
            description: 'Saat sembelit, meningkatkan asupan makanan yang kaya serat atau mengonsumsi obat pencahar bisa dilakukan. Akan tetapi, beberapa orang memilih untuk mengonsumsi suplemen vitamin untuk mengatasi sembelit. Berikut ini merupakan beberapa vitamin dan efeknya terhadap kesehatan pencernaan: Vitamin C Studi di tahun 2008 memerhatikan bahwa anak-anak dengan konstipasi memiliki kadar vitamin C, folat, dan magnesium yang rendah. Anak-anak ini juga kurang mengonsumsi serat makanan, buah-buahan, dan makanan nabati. Kurangnya konsumsi serat dapat menyebabkan konstipasi. Buah-buahan dan sayuran yang tinggi serat sering kali juga tinggi vitamin C. Akan tetapi, kelebihan vitamin C dapat menyebabkan sakit perut, mual, muntah, dan diare. Semakin besar dosisnya, semakin besar juga kemungkinan seseorang mengalami gejala-gejala ini. Dokter tidak menyarankan seseorang mengonsumsi vitamin C dosis tinggi untuk membantu mereka yang mengalami sembelit. Akan tetapi, asupan vitamin C&nbsp; yang sesuai kebutuhan harian bisa membantu.',
            category: 'Diet',
            image: 'mask.jpg',
            date: '08 Sep 2021'
        },
        {
            title: 'Peneliti Temukan Metabolisme Tubuh Tidak Menurun Hingga Usia 60',
            timestamp: '',
            description: 'Banyak yang beranggapan bahwa menjadi lebih sulit untuk menurunkan berat badan seiring bertambahnya usia. Tetapi sebuah studi baru telah membantah klaim tersebut, menunjukkan bahwa metabolisme tetap stabil antara usia 20 dan 60 tahun. Studi yang diterbitkan di jurnal Science, melihat data yang diambil dari 6.421 peserta selama 40 tahun, untuk melihat bagaimana faktor-faktor termasuk ukuran, jenis kelamin dan usia mempengaruhi metabolisme. Temuan menunjukkan bahwa sementara usia memang berperan dalam seberapa cepat orang membakar kalori, itu tidak memiliki banyak dampak pada metabolisme seperti yang diperkirakan sebelumnya.Tingkat metabolisme benar-benar stabil sepanjang kehidupan dewasa, 20 hingga 60 tahun, penulis studi Herman Pontzer, seorang profesor antropologi evolusi di Duke University di AS.“Tidak ada efek menopause yang bisa kita lihat, misalnya. Dan, Anda tahu, orang akan berkata, Saat saya menginjak usia 30 tahun, metabolisme saya berantakan. Kami tidak melihat bukti untuk itu, sebenarnya. Para peneliti menemukan bahwa total pengeluaran energi harian dan pengeluaran basal - energi yang dibutuhkan untuk menjalankan fungsi metabolisme mendasar seperti pernapasan - meningkat seiring dengan ukuran tubuh.Dengan mempertimbangkan hal ini, mereka menyimpulkan bahwa bayi hingga usia satu bulan menggunakan jumlah total energi yang sama per hari dengan orang dewasa, tetapi pada usia sekitar satu tahun, ini meningkat dengan cepat menjadi sekitar 50 persen lebih tinggi daripada orang dewasa.Namun, setelah usia tersebut, para peneliti menemukan bahwa total pengeluaran energi harian menurun secara perlahan melalui masa kanak-kanak dan remaja dengan laju sekitar -2,8 persen, hingga tingkat dewasa tercapai pada usia 20 tahun. Sejak usia 20 tahun, para peneliti menemukan bahwa total pengeluaran energi harian tetap stabil sampai sekitar usia 60 tahun, saat itu mulai menurun sekali lagi.Faktor-faktor termasuk kehamilan dan menopause tidak berpengaruh pada tingkat metabolisme, studi menyimpulkan. Para peneliti menyimpulkan bahwa anak-anak cenderung lebih aktif daripada orang dewasa, yang mengarah ke metabolisme yang lebih tinggi.&nbsp; Namun, remaja, terlepas dari stereotip bahwa mereka makan lebih banyak selama tahun-tahun pertumbuhan mereka, tidak memiliki tingkat metabolisme yang jauh lebih tinggi daripada orang dewasa. Sebelumnya ada anggapan bahwa metabolisme mungkin melambat di usia 30-an dan itu kemudian dianggap [menyebabkan] kerentanan terhadap penyebaran usia paruh baya, salah satu penulis studi, Profesor John Speakman dari University of Aberdeen di Inggris.&nbsp; Kami tidak menemukan bukti yang mendukung itu. Jadi, jika Anda menambah berat badan dan lingkar pinggang Anda membesar selama usia 30-an dan 40-an, itu mungkin karena Anda makan lebih banyak, lalu menghabiskan lebih sedikit energi, pungkasnya.',
            category: 'Gaya Hidup',
            image: 'online meet-article-1631057430.jpg',
            date: '09 Sep 2021'
        },
        {
            title: 'Vitamin',
            timestamp: '',
            description: 'Banyak yang beranggapan bahwa menjadi lebih sulit untuk menurunkan berat badan seiring bertambahnya usia. Tetapi sebuah studi baru telah membantah klaim tersebut, menunjukkan bahwa metabolisme tetap stabil antara usia 20 dan 60 tahun. Studi yang diterbitkan di jurnal Science, melihat data yang diambil dari 6.421 peserta selama 40 tahun, untuk melihat bagaimana faktor-faktor termasuk ukuran, jenis kelamin dan usia mempengaruhi metabolisme. Temuan menunjukkan bahwa sementara usia memang berperan dalam seberapa cepat orang membakar kalori, itu tidak memiliki banyak dampak pada metabolisme seperti yang diperkirakan sebelumnya.Tingkat metabolisme benar-benar stabil sepanjang kehidupan dewasa, 20 hingga 60 tahun, penulis studi Herman Pontzer, seorang profesor antropologi evolusi di Duke University di AS.“Tidak ada efek menopause yang bisa kita lihat, misalnya. Dan, Anda tahu, orang akan berkata, Saat saya menginjak usia 30 tahun, metabolisme saya berantakan. Kami tidak melihat bukti untuk itu, sebenarnya. Para peneliti menemukan bahwa total pengeluaran energi harian dan pengeluaran basal - energi yang dibutuhkan untuk menjalankan fungsi metabolisme mendasar seperti pernapasan - meningkat seiring dengan ukuran tubuh.Dengan mempertimbangkan hal ini, mereka menyimpulkan bahwa bayi hingga usia satu bulan menggunakan jumlah total energi yang sama per hari dengan orang dewasa, tetapi pada usia sekitar satu tahun, ini meningkat dengan cepat menjadi sekitar 50 persen lebih tinggi daripada orang dewasa.Namun, setelah usia tersebut, para peneliti menemukan bahwa total pengeluaran energi harian menurun secara perlahan melalui masa kanak-kanak dan remaja dengan laju sekitar -2,8 persen, hingga tingkat dewasa tercapai pada usia 20 tahun. Sejak usia 20 tahun, para peneliti menemukan bahwa total pengeluaran energi harian tetap stabil sampai sekitar usia 60 tahun, saat itu mulai menurun sekali lagi.Faktor-faktor termasuk kehamilan dan menopause tidak berpengaruh pada tingkat metabolisme, studi menyimpulkan. Para peneliti menyimpulkan bahwa anak-anak cenderung lebih aktif daripada orang dewasa, yang mengarah ke metabolisme yang lebih tinggi.&nbsp; Namun, remaja, terlepas dari stereotip bahwa mereka makan lebih banyak selama tahun-tahun pertumbuhan mereka, tidak memiliki tingkat metabolisme yang jauh lebih tinggi daripada orang dewasa. Sebelumnya ada anggapan bahwa metabolisme mungkin melambat di usia 30-an dan itu kemudian dianggap [menyebabkan] kerentanan terhadap penyebaran usia paruh baya, salah satu penulis studi, Profesor John Speakman dari University of Aberdeen di Inggris.&nbsp; Kami tidak menemukan bukti yang mendukung itu. Jadi, jika Anda menambah berat badan dan lingkar pinggang Anda membesar selama usia 30-an dan 40-an, itu mungkin karena Anda makan lebih banyak, lalu menghabiskan lebih sedikit energi, pungkasnya.',
            category: 'Vitamin',
            image: 'multivitamin.jpg',
            date: '09 Sep 2021'
        },
        {
            title: 'Vaksin',
            timestamp: '',
            description: 'Banyak yang beranggapan bahwa menjadi lebih sulit untuk menurunkan berat badan seiring bertambahnya usia. Tetapi sebuah studi baru telah membantah klaim tersebut, menunjukkan bahwa metabolisme tetap stabil antara usia 20 dan 60 tahun. Studi yang diterbitkan di jurnal Science, melihat data yang diambil dari 6.421 peserta selama 40 tahun, untuk melihat bagaimana faktor-faktor termasuk ukuran, jenis kelamin dan usia mempengaruhi metabolisme. Temuan menunjukkan bahwa sementara usia memang berperan dalam seberapa cepat orang membakar kalori, itu tidak memiliki banyak dampak pada metabolisme seperti yang diperkirakan sebelumnya.Tingkat metabolisme benar-benar stabil sepanjang kehidupan dewasa, 20 hingga 60 tahun, penulis studi Herman Pontzer, seorang profesor antropologi evolusi di Duke University di AS.“Tidak ada efek menopause yang bisa kita lihat, misalnya. Dan, Anda tahu, orang akan berkata, Saat saya menginjak usia 30 tahun, metabolisme saya berantakan. Kami tidak melihat bukti untuk itu, sebenarnya. Para peneliti menemukan bahwa total pengeluaran energi harian dan pengeluaran basal - energi yang dibutuhkan untuk menjalankan fungsi metabolisme mendasar seperti pernapasan - meningkat seiring dengan ukuran tubuh.Dengan mempertimbangkan hal ini, mereka menyimpulkan bahwa bayi hingga usia satu bulan menggunakan jumlah total energi yang sama per hari dengan orang dewasa, tetapi pada usia sekitar satu tahun, ini meningkat dengan cepat menjadi sekitar 50 persen lebih tinggi daripada orang dewasa.Namun, setelah usia tersebut, para peneliti menemukan bahwa total pengeluaran energi harian menurun secara perlahan melalui masa kanak-kanak dan remaja dengan laju sekitar -2,8 persen, hingga tingkat dewasa tercapai pada usia 20 tahun. Sejak usia 20 tahun, para peneliti menemukan bahwa total pengeluaran energi harian tetap stabil sampai sekitar usia 60 tahun, saat itu mulai menurun sekali lagi.Faktor-faktor termasuk kehamilan dan menopause tidak berpengaruh pada tingkat metabolisme, studi menyimpulkan. Para peneliti menyimpulkan bahwa anak-anak cenderung lebih aktif daripada orang dewasa, yang mengarah ke metabolisme yang lebih tinggi.&nbsp; Namun, remaja, terlepas dari stereotip bahwa mereka makan lebih banyak selama tahun-tahun pertumbuhan mereka, tidak memiliki tingkat metabolisme yang jauh lebih tinggi daripada orang dewasa. Sebelumnya ada anggapan bahwa metabolisme mungkin melambat di usia 30-an dan itu kemudian dianggap [menyebabkan] kerentanan terhadap penyebaran usia paruh baya, salah satu penulis studi, Profesor John Speakman dari University of Aberdeen di Inggris.&nbsp; Kami tidak menemukan bukti yang mendukung itu. Jadi, jika Anda menambah berat badan dan lingkar pinggang Anda membesar selama usia 30-an dan 40-an, itu mungkin karena Anda makan lebih banyak, lalu menghabiskan lebih sedikit energi, pungkasnya.',
            category: 'Vaksinasi',
            image: 'virus.png',
            date: '09 Sep 2021'
        }
    ]
})

const getters = {
    getArticles: state => state.articles
}

const actions = {}

const mutations = {}

export default {
  state,
  getters,
  actions,
  mutations,
  namespaced: true
}
